# Generated by Django 4.2.9 on 2025-08-17 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alexienu', '0002_account_account_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['user', '-id'], 'verbose_name_plural': 'Journal entries'},
        ),
    ]
