# Generated by Django 4.2.9 on 2025-08-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alexienu', '0003_alter_journalentry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=22),
            preserve_default=False,
        ),
    ]
